
import { StyleSheet,ImageStyle,ViewStyle,TextStyle } from "react-native";

interface AccountProps{
    container:ViewStyle
    topContainer:ViewStyle
    bottomContainer:ViewStyle
    topOptionsBox:ViewStyle
    nameUserBox:ViewStyle
    btnSignIn:ViewStyle
    btnOptionsContainer:ViewStyle
    boxBtns:ViewStyle
    btnOptionLogin:ViewStyle
    nameDataUser:ViewStyle
    bubbleUser:ViewStyle
    btnMenuTop:ViewStyle
    backgroundTopContainer:ViewStyle
    headerSignAccess:ViewStyle
    getInWithPassBtn:ViewStyle
    putCredentialsContainer:ViewStyle
    btnAccessPass:ViewStyle
    inputData:TextStyle
    eyePass:ViewStyle
}
const loginStyles : AccountProps = StyleSheet.create({
    container:{
        width:'100%',
        height:'100%',
        display:'flex',
        flexDirection:'column',
        justifyContent:'space-between',
        alignItems:'center',      
    },
    topContainer:{
        width:'100%',
        height:'50%',
        display:'flex',
        flexDirection:'column',
        justifyContent:'space-around',
        alignItems:'center',
        backgroundColor:'#004274'
    },
    backgroundTopContainer:{
        width:'100%',
        height:'100%',
        display:'flex',
        flexDirection:'column',
        justifyContent:'space-around',
        alignItems:'center',
    },
    bottomContainer:{
        width:'100%',
        height:'50%',
    },
    topOptionsBox:{
        width:'90%',
        height:'15%',        
        display:'flex',
        justifyContent:'space-between',
        flexDirection:'row',
        alignItems:'center',        
    },
    btnMenuTop:{
        width:'15%',
        height:'100%',
        display:'flex',
        justifyContent:'center',
        flexDirection:'column',
        alignItems:'center'
    },  
    nameUserBox:{
        width:'90%',
        height:60,       
        display:'flex',
        justifyContent:'space-between',
        alignItems:'center',
        flexDirection:'row',
        
    },
    nameDataUser:{
        width:'auto',
        height:'100%',
        display:'flex',
        flexDirection:'column',
        justifyContent:'space-between',
        alignItems:'flex-start'
    },
    bubbleUser:{
        width:50,
        height:50,
        borderRadius:50,
        backgroundColor:'#49a5e6',
        display:'flex',
        justifyContent:'center',
        alignItems:'center'
    },
    btnSignIn:{
        width:'90%',
        height:40,
        display:'flex',
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:'#ffffff',
        marginBottom:20
    },
    btnOptionsContainer:{
        width:'90%',
        height:'20%',       
        display:'flex',
        flexDirection:'row',
        justifyContent:'flex-start',
        alignItems:'center',
        marginBottom:10
    },
    boxBtns:{
        width:'20%',
        height:'100%',
        display:'flex',
        flexDirection:'column',
        justifyContent:'space-between',
        alignItems:'center',
        marginLeft:10
    },
    btnOptionLogin:{
        width:50,
        height:50,
        borderRadius:50,     
        backgroundColor:'#004286'      
    },
    headerSignAccess:{
        width:'95%',
        height:50,       
        display:'flex',
        justifyContent:'space-between',
        alignItems:'center',
        flexDirection:'row'
    },
    putCredentialsContainer:{
        width:'95%',
        height:'30%',
        
        display:'flex',
        justifyContent:'space-between',
        alignItems:'center',
        flexDirection:'column',
    },
    getInWithPassBtn:{
        width:'95%',
        height:'60%',
        
        display:'flex',
        justifyContent:'center',
        alignItems:'center'
    },
    btnAccessPass:{
        width:'100%',
        height:50,
        display:'flex',
        justifyContent:'center',
        alignItems:'center'
    },
    inputData:{
        width:'100%',
        height:60,
        borderBottomColor:'#ffffff',
        borderBottomWidth:1,
        paddingLeft:10,
        backgroundColor:'#004481',
        color:'#ffffff'
    },
    eyePass:{
        width:'10%',
        height:60,        
        tintColor:'#075b99',
        borderBottomColor:'#ffffff',
        borderBottomWidth:1,
        backgroundColor:'#004481'        
    },
})
export default loginStyles