import { StyleSheet,ImageStyle,ViewStyle,TextStyle } from "react-native";

interface NotificationProps{
    container:ViewStyle
    topTitleContainer:ViewStyle
    topTittleName:TextStyle
    cancelBtnTop:ViewStyle
    bottomOptionsDisplay:ViewStyle
    mainInformationDisplay:ViewStyle
    mainBoxesFinalInfo:ViewStyle
    mainBoxesBigInfo:ViewStyle
    mainBoxesBigInfoTitle:ViewStyle
    mainBoxesBigInfoData:ViewStyle
    mainBoxesBigInfoDataDisplay:ViewStyle
    mainBoxesFinalInfoDataDisplay:ViewStyle
    btnSizeDisplay:ViewStyle
    tokenInfoContainer:ViewStyle
    tokenTopInfoContainer:ViewStyle
    tokenMainInfo:ViewStyle
    tokenButtonsContainer:ViewStyle
    resumeInputBoxAmount:ViewStyle
    topBoxInformationTicket:ViewStyle
    topBoxBigInfoTicket:ViewStyle
    bottomBoxInformationTicket:ViewStyle
    bottomBoxBigInfoTicket:ViewStyle
    btnGif:ViewStyle
    ticketAccountData:ViewStyle
    tickeAccountInfo:ViewStyle
    boxAlertAboutNews:ViewStyle
    boxAlertContainer:ViewStyle
    lastOptionNotificationView:ViewStyle
    bubbleUser:ViewStyle
    bubbleTicket:ViewStyle
    amountAccountContainer:ViewStyle
    valueSymbol:TextStyle
    valueNumber:TextStyle
    dateTextTitle:TextStyle
    dateTextTitleInformation:TextStyle
    dateAmountIformation:TextStyle
    ticketAccountDataContainerInfo:ViewStyle
    shareBtn:ViewStyle
    iconsAlert:ImageStyle
    mainScrollContainer:ViewStyle
    agreeTextBtn:TextStyle
}
const notificationStyles : NotificationProps = StyleSheet.create({
    container:{
        width:'100%',
        height:'100%',
        display:'flex',
        flexDirection:'column',
        justifyContent:'space-between',
        alignItems:'center',
        backgroundColor:'#ffffff'
    },
    topTitleContainer:{
        width:'100%',
        height:60,
        display:'flex',
        flexDirection:'row',
        justifyContent:'flex-end',
        alignItems:'center',     
        position:'relative',
        backgroundColor:'#004481'
    },
    topTittleName:{
        width:'auto',
        height:'auto',
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: [{ translateX: '-50%' }, { translateY: '-50%' }],
        fontSize:18,
        color:'#ffffff',
        fontWeight:100
    },
    cancelBtnTop:{
        width:40,
        height:'100%',
        display:'flex',
        justifyContent:'center',
        alignItems:'center',
    },
    mainInformationDisplay:{
        width:'100%',
        height:'70%',        
        marginBottom:'auto',
        display:'flex',
        justifyContent:'space-between',
        flexDirection:'column',
        alignItems:'center',
        backgroundColor:'#004481'
    },
    bottomOptionsDisplay:{
        width:'100%',
        height:'20%',         
        display:'flex' ,
        justifyContent:'space-around',
        alignItems:'center',
        flexDirection:'column'
    },
    mainBoxesBigInfo:{
        width:'100%',
        height:'22%',
        borderBottomColor:'#ffffff',
        borderBottomWidth:1,
        display:'flex',
        justifyContent:'space-around',
        flexDirection:'column',
        alignItems:'center',
    },
    mainBoxesBigInfoTitle:{
        width:'90%',
        height:'20%',      
        display:'flex',
        justifyContent:'space-between',
        flexDirection:'row',
        alignItems:'center'
    },
    mainBoxesBigInfoData:{
        width:'90%',
        height:'70%',          
        display:'flex',
        justifyContent:'space-between',
        flexDirection:'row',
        alignItems:'center'
    },
    mainBoxesBigInfoDataDisplay:{
        width:'45%',
        height:'100%',        
        display:'flex',
        justifyContent:'space-around',
        flexDirection:'column',
        alignItems:'center'
    },
    mainBoxesFinalInfo:{
        width:'100%',
        height:'34%',
        display:'flex',
        flexDirection:'column',
        justifyContent:'space-between',
        alignItems:'center'
    },
    mainBoxesFinalInfoDataDisplay:{
        width:'45%',
        height:'100%',        
        display:'flex',
        justifyContent:'flex-start',
        flexDirection:'column',
        rowGap:10
    },
    btnSizeDisplay:{
        width:140,
        height:50,
        backgroundColor:'#55aee8',
        display:'flex',
        justifyContent:'center',
        alignItems:'center'
    },
    tokenInfoContainer:{
        width:'100%',
        height:'65%',        
        display:'flex',
        justifyContent:'space-between',
        alignItems:'center'
    },
    tokenTopInfoContainer:{
        width:'100%',
        height:'35%',      
        display:'flex',
        flexDirection:'column',
        justifyContent:'space-between',
        alignItems:'center',
        backgroundColor:'#9b7239'
    },
    tokenMainInfo:{
        width:'90%',
        height:'30%',         
        display:'flex',
        justifyContent:'space-around',
        flexDirection:'column',
        alignItems:'center'
    },
    tokenButtonsContainer:{
        width:'auto',
        height:'auto',
        display:'flex',
        flexDirection:'column',
        justifyContent:'center',
        alignItems:'center'
    },
    resumeInputBoxAmount:{
        width:'100%',
        height:50,        
        display:'flex',
        justifyContent:'flex-start',
        alignItems:'center',
        flexDirection:'row',
        backgroundColor:'#efefef'
    },
    topBoxInformationTicket:{
        width:'100%',
        height:'20%',        
        display:'flex',
        flexDirection:'column',
        justifyContent:'space-between',
        alignItems:'center',
        backgroundColor:'#038715'
    },
    topBoxBigInfoTicket:{
        width:'100%',
        height:'65%',
        display:'flex',
        flexDirection:'column',
        justifyContent:'space-around',
        alignItems:'center',       
        marginBottom:'auto'
    },
    bottomBoxInformationTicket:{
        width:'100%',
        height:'40%',        
        display:'flex',
        flexDirection:'column',
        justifyContent:'flex-end',
        alignItems:'center',
        position:'relative',
        marginBottom:'auto'
    },
    btnGif:{
        width:120,
        height:50,
        position: 'absolute',
        top: '0%',
        left: '50%',
        transform: [{ translateX: '-50%' }, { translateY: '-50%' }],
        borderRadius:25,      
        overflow:'hidden',
        display:'flex',
        justifyContent:'space-around',
        alignItems:'center',
        flexDirection:'row'
    },
    bottomBoxBigInfoTicket:{
        width:'100%',
        height:'87%',
        display:'flex',
        justifyContent:'space-between',
        flexDirection:'column',
        alignItems:'center',              
    },
    ticketAccountData:{
        width:'100%',
        height:'14%',       
        display:'flex',
        justifyContent:'center',
        flexDirection:'row',
        alignItems:'center',
        columnGap:15,
        marginTop:5
    },
    tickeAccountInfo:{
        width:'100%',
        height:'12%',       
        display:'flex',
        justifyContent:'space-around',
        flexDirection:'column',
        alignItems:'center',        
    },
    boxAlertContainer:{
        width:'100%',
        height:'25%',        
        display:'flex',
        justifyContent:'space-between',
        alignItems:'center',
        flexDirection:'column',    
    },
    boxAlertAboutNews:{
        width:'95%',
        display:'flex',
        justifyContent:'space-around',
        alignItems:'center',
        flexDirection:'column',
        backgroundColor:'#d0e9fd'
    },
    lastOptionNotificationView:{
        width:'100%',
        height:'12%',
        display:'flex',
        flexDirection:'column',
        justifyContent:'space-between',
        alignItems:'center',
    },
    bubbleUser:{
        width:50,
        height:50,
        borderRadius:50,
        backgroundColor:'#49a5e6',
        display:'flex',
        justifyContent:'center',
        alignItems:'center'
    },
    bubbleTicket:{
        width:35,height:35,
        backgroundColor:'#f98c06',
        borderRadius:35,
        display:'flex',
        justifyContent:'center',
        alignItems:'center'
    },
    amountAccountContainer:{
        width:'auto',
        height:'auto',
        display:'flex',
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center'
    },
    valueSymbol:{
        fontSize:14,
        width:15,
        height:'auto',
        textAlign:'center',
        marginBottom:5,
        color:'#ffffff'
    },
    valueNumber:{
        fontSize:22,
        width:'auto',
        height:'auto',
        color:'#ffffff'

    },
    dateTextTitle:{
        width:'auto',
        height:'auto',
        fontSize:16,
        fontWeight:'bold',
        color:'#ffffff'
    },
    dateTextTitleInformation:{
        width:'auto',
        height:'auto',
        fontSize:16,
        color:'#ffffff',
        fontWeight:100
    },
    dateAmountIformation:{
        width:'auto',
        height:'auto',
        fontSize:24,
        color:'#ffffff'
    },
    ticketAccountDataContainerInfo:{
        width:'auto',
        height:'100%',
        display:'flex',
        flexDirection:'column',
        justifyContent:'flex-start',
        alignItems:'flex-end',
        rowGap:4
    },
    shareBtn:{
        height:'auto',
        width:'auto',
        rowGap:5,
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
        justifyContent:'center',
        marginTop:10
    },
    iconsAlert:{
        width:20,
        height:20
    },
    mainScrollContainer:{
        width:'100%',
        height:'180%',
        display:'flex',
        flexDirection:'column',
        justifyContent:'space-between',
        alignItems:'center',
        backgroundColor:'#ffffff'
    },
    agreeTextBtn:{
        width:'auto',
        height:'auto',
        color:'#ffffff',
        fontWeight:'bold'
    }
})
export default notificationStyles